# Generated by Django 5.0.7 on 2024-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_patient_address_patient_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="available_times",
            field=models.TextField(blank=True, null=True),
        ),
    ]
