# Generated by Django 5.0.7 on 2024-08-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_doctor_bio_doctor_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
    ]
