# Generated by Django 5.0.7 on 2024-08-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_category_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
    ]
