# Generated by Django 5.0.7 on 2024-08-08 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_appointment_doctor_alter_appointment_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
